// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: Index

#ifndef _INDEX_UI_H
#define _INDEX_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_Index
void ui_Index_screen_init(void);
extern lv_obj_t *ui_Index;
extern lv_obj_t *ui_circle1;
extern lv_obj_t *ui_circle2;
extern lv_obj_t *ui_circle3;
extern lv_obj_t *ui_circle4;
extern lv_obj_t *ui_welcome_label;
extern lv_obj_t *ui_progress;
extern lv_obj_t *ui____initial_actions0;



LV_FONT_DECLARE( ui_font_kanit60);

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
