// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: Index

#include "../ui.h"

void ui_Index_screen_init(void)
{
ui_Index = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Index, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Index, lv_color_hex(0xECF0F1), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Index, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_circle1 = lv_obj_create(ui_Index);
lv_obj_set_width( ui_circle1, 100);
lv_obj_set_height( ui_circle1, 100);
lv_obj_set_x( ui_circle1, -138 );
lv_obj_set_y( ui_circle1, 68 );
lv_obj_set_align( ui_circle1, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_circle1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_circle1, 1000, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_circle1, lv_color_hex(0x3498DB), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_circle1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_circle1, lv_color_hex(0x2ECC71), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_main_stop(ui_circle1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_stop(ui_circle1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_dir(ui_circle1, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_circle1, LV_BORDER_SIDE_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_circle2 = lv_obj_create(ui_Index);
lv_obj_set_width( ui_circle2, 100);
lv_obj_set_height( ui_circle2, 100);
lv_obj_set_x( ui_circle2, 151 );
lv_obj_set_y( ui_circle2, -81 );
lv_obj_set_align( ui_circle2, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_circle2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_circle2, 1000, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_circle2, lv_color_hex(0xF4D03F), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_circle2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_circle2, lv_color_hex(0x2ECC71), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_main_stop(ui_circle2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_stop(ui_circle2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_dir(ui_circle2, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_circle2, LV_BORDER_SIDE_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_circle3 = lv_obj_create(ui_Index);
lv_obj_set_width( ui_circle3, 30);
lv_obj_set_height( ui_circle3, 30);
lv_obj_set_x( ui_circle3, 93 );
lv_obj_set_y( ui_circle3, 55 );
lv_obj_set_align( ui_circle3, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_circle3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_circle3, 1000, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_circle3, lv_color_hex(0x8E44AD), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_circle3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_circle3, lv_color_hex(0xE74C3C), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_main_stop(ui_circle3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_stop(ui_circle3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_dir(ui_circle3, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_circle3, LV_BORDER_SIDE_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_circle4 = lv_obj_create(ui_Index);
lv_obj_set_width( ui_circle4, 60);
lv_obj_set_height( ui_circle4, 60);
lv_obj_set_x( ui_circle4, -65 );
lv_obj_set_y( ui_circle4, -59 );
lv_obj_set_align( ui_circle4, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_circle4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_circle4, 1000, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_circle4, lv_color_hex(0x2C3E50), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_circle4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_circle4, lv_color_hex(0xD35400), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_main_stop(ui_circle4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_stop(ui_circle4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_dir(ui_circle4, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_circle4, LV_BORDER_SIDE_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_welcome_label = lv_label_create(ui_Index);
lv_obj_set_width( ui_welcome_label, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_welcome_label, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_welcome_label, LV_ALIGN_CENTER );
lv_label_set_text(ui_welcome_label,"สวัสดี");
lv_obj_set_style_text_color(ui_welcome_label, lv_color_hex(0x2C3E50), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_welcome_label, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_welcome_label, &ui_font_kanit60, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_progress = lv_bar_create(ui_Index);
lv_bar_set_value(ui_progress,25,LV_ANIM_OFF);
lv_obj_set_width( ui_progress, 150);
lv_obj_set_height( ui_progress, 10);
lv_obj_set_x( ui_progress, 0 );
lv_obj_set_y( ui_progress, 40 );
lv_obj_set_align( ui_progress, LV_ALIGN_CENTER );


}
